# Change these first
owner: tarper24 # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: tarper24
    url: https://tarper24.net

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.t24.co
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: tarper24 Status
  introTitle: "**tarper24's system status**, powered by [GitHub](https://github.com/)."
  introMessage: |
    **What is this page?**

    This page is used by tarper24 to keep track of his websites' uptimes. It uses real-time data from GitHub with [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/tarper24/upptime
  theme: night
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
